spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: 12345

  mail:
    host: smtp.gmail.com
    port: 587
    username: dkemailsend@gmail.com
    password: "muuw ffke unoq zhko"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  cache:
    type: caffeine

naver:
  client-id: 7iFtt_F85UDT1CbXwKHr
  client-secret: otX6iaNvRN

caffeine:
  spec: expireAfterWrite=1h

jwt:
  secret: zK9bW9o2h9wV+y2hRXnWLR8iTrWkB13vghH4L1exbws=



mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
