server:
  port: 8080
spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.219.100:1521/XEPDB1
    username: system      # SYSTEM 대신 앱 계정 권장
    password: 1234
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 5       # 커넥션 풀 제한
      minimum-idle: 1
      connection-timeout: 20000   
      idle-timeout: 30000
      max-lifetime: 1800000
      validation-timeout: 3000   # 커넥션 유효성 체크 최대 3초

  mail:
    host: smtp.gmail.com
    port: 587
    username: dkemailsend@gmail.com
    password: "ktlk eznc snev fxsc"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  cache:
    type: caffeine

naver:
  client-id: 7iFtt_F85UDT1CbXwKHr
  client-secret: otX6iaNvRN

caffeine:
  spec: expireAfterWrite=1h

jwt:
  secret: zK9bW9o2h9wV+y2hRXnWLR8iTrWkB13vghH4L1exbws=



mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
