server:
  port: 8080
spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.219.100:1521/XEPDB1
    username: system
    password: 1234

 

  mail:
    host: smtp.gmail.com
    port: 587
    username: dkemailsend@gmail.com
    password: "ktlk eznc snev fxsc"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  cache:
    type: caffeine

naver:
  client-id: 7iFtt_F85UDT1CbXwKHr
  client-secret: otX6iaNvRN

caffeine:
  spec: expireAfterWrite=1h

jwt:
  secret: zK9bW9o2h9wV+y2hRXnWLR8iTrWkB13vghH4L1exbws=



mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
